version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.14
        environment:
          VAULT_ADDR: "http://localhost:8200"
          VAULT_TOKEN: root
          VAULT_TEST_TOKEN: root
          VAULT_DEV_ALREADY_RUNNING: 1
    working_directory: /go/src/github.com/dollarshaveclub/pvc
    steps:
      - checkout
      - run: go build 
  test:
    docker:
      - image: circleci/golang:1.14
        environment:
          VAULT_ADDR: "http://vault:8200"
          VAULT_TEST_TOKEN: root
          VAULT_DEV_ALREADY_RUNNING: 1
      - image: quay.io/dollarshaveclub/vault-dev:master
        name: vault
        environment:
          VAULT_API_ADDR: "http://0.0.0.0:8200"
          VAULT_SECRETS_FILE: /go/src/github.com/dollarshaveclub/pvc/testing/vault_secrets.json
          VAULT_POLICIES_FILE: /go/src/github.com/dollarshaveclub/pvc/testing/vault_policies.json
          
    steps:
      - checkout
      - run:
          name: Running tests
          command: go test -v -race -cover

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
