version: 2.1

executors:
  gobuild:
    docker:
      - image: circleci/golang:1.14
        environment:
          VAULT_ADDR: "http://vault:8200"
          VAULT_TOKEN: root
          VAULT_TEST_APPID: testing
          VAULT_TEST_USERID: asdf
          VAULT_TEST_TOKEN: root
          VAULT_DEV_ALREADY_RUNNING: 1
    working_directory: /go/src/github.com/dollarshaveclub/pvc
    
  vault:
    docker:
      - image: quay.io/dollarshaveclub/vault-dev:master
        name: vault
        environment:        
          VAULT_USE_APP_ID: 1
          VAULT_SECRETS_FILE: /tmp/opt/secrets.json
          VAULT_APP_ID_FILE: /tmp/opt/app-id.json
          VAULT_POLICIES_FILE: /tmp/opt/policies.json
        
    
jobs:
  flow:
    executor: gobuild
    steps: 
      - checkout
      - run: go build
      - run: mkdir -p /tmp/opt
      - run: ls ./testing
      - run: cp /go/src/github.com/dollarshaveclub/pvc/testing/vault_secrets.json /tmp/opt/secrets.json
      - run: cp /go/src/github.com/dollarshaveclub/pvc/testing/vault_app_ids.json /tmp/opt/app-id.json
      - run: cp /go/src/github.com/dollarshaveclub/pvc/testing/vault_policies.json /tmp/opt/policies.json
      - run: ls /tmp/opt
      - persist_to_workspace: 
          root: /tmp/opt
          paths:
            - secrets.json
            - policies.json
            - app-id.json
     
  downstream:
    executor: vault
    steps: 
      - attach_workspace:
          at: /tmp/opt
      - run: ls /tmp
      - run: ls /opt
      - run: ls /tmp/opt
      - run: 
          name: Start Vault
          command: /opt/run.sh
          background: true

  test: 
    executor: gobuild
    steps:
      - checkout
      - run: go test -v -race -cover

workflows:
  version: 2

  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow 
      - test:
          requires:
            - downstream
    