version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.14
        environment:
          VAULT_ADDR: "http://localhost:8200"
          VAULT_TOKEN: root
          VAULT_TEST_APPID: testing
          VAULT_TEST_USERID: asdf
          VAULT_TEST_TOKEN: root
          VAULT_DEV_ALREADY_RUNNING: 1
    working_directory: /go/src/github.com/dollarshaveclub/pvc
    steps:
      - checkout
      - run: go build 
  test:
    docker:
      - image: circleci/golang:1.14
        environment:
          VAULT_ADDR: "http://vault:8200"
          VAULT_TOKEN: root
          VAULT_TEST_APPID: testing
          VAULT_TEST_USERID: asdf
          VAULT_TEST_TOKEN: root
          VAULT_DEV_ALREADY_RUNNING: 1
      - image: quay.io/dollarshaveclub/vault-dev:master
        environment: 
          VAULT_USE_APP_ID: 1
        command: |
          run --volumes-from vault-dev-opts -d --name vault -p 8200:8200

    working_directory: /go/src/github.com/dollarshaveclub/pvc
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: |
          docker create -v /opt --name vault-dev-opts alpine:3.4 /bin/true
          docker cp ./testing/vault_app_ids.json vault-dev-opts:/opt/app-id.json
          docker cp ./testing/vault_secrets.json vault-dev-opts:/opt/secrets.json
          docker cp ./testing/vault_policies.json vault-dev-opts:/opt/policies.json
      - run:
          name: Running tests
          command: go test -v -race -cover

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
