version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.14
        environment:
          VAULT_ADDR: "http://localhost:8200"
          VAULT_TOKEN: root
          VAULT_TEST_APPID: testing
          VAULT_TEST_USERID: asdf
          VAULT_TEST_TOKEN: root
          VAULT_DEV_ALREADY_RUNNING: 1
    working_directory: /go/src/github.com/dollarshaveclub/pvc
    steps:
      - checkout
      - run: go build 
  test:
    docker:
      - image: circleci/golang:1.14
        environment:
          VAULT_ADDR: "http://localhost:8200"
          VAULT_TOKEN: root
          VAULT_TEST_APPID: testing
          VAULT_TEST_USERID: asdf
          VAULT_TEST_TOKEN: root
          VAULT_DEV_ALREADY_RUNNING: 1
      - image: quay.io/dollarshaveclub/vault-dev:master
        environment:
          VAULT_USE_APP_ID: 1
          VAULT_SECRETS_FILE: /go/src/github.com/dollarshaveclub/pvc/testing/vault_secrets.json
          VAULT_APP_ID_FILE: /go/src/github.com/dollarshaveclub/pvc/testing/app_vault_app_ids.json
          VAULT_POLICIES_FILE: /go/src/github.com/dollarshaveclub/pvc/testing/vault_policies.json
    working_directory: /go/src/github.com/dollarshaveclub/pvc
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          name: Running tests
          command: go test -v -race -cover

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
