version: 2.1

executors:
  gobuild:
    docker:
      - image: circleci/golang:1.14
        environment:
          VAULT_ADDR: "http://localhost:8200"
          VAULT_TOKEN: root
          VAULT_TEST_APPID: testing
          VAULT_TEST_USERID: asdf
          VAULT_TEST_TOKEN: root
          VAULT_DEV_ALREADY_RUNNING: 1
    working_directory: /go/src/github.com/dollarshaveclub/pvc
    
  vault:
    docker:
      - image: quay.io/dollarshaveclub/vault-dev:master
        environment:
          VAULT_USE_APP_ID: 1
        
    
jobs:
  flow:
    executor: gobuild
    steps: 
      - checkout
      - run: go build
      - run: mkdir -p /tmp/opt
      - run: cp /go/src/github.com/dollarshaveclub/pvc/testing/vault_secrets.json /tmp/opt/secrets.json
      - persist_to_workspace: 
          root: /tmp/opt
          paths:
            - secrets.json
     
  downstream:
    executor: vault
    steps: 
      - attach_workspace:
          at: /tmp
      - run: ls /tmp
      - run: ls /opt
      # - run: /opt/run.sh
      #   background: true

  test: 
    executor: gobuild
    steps:
      - checkout
      - run: go test -v -race -cover

workflows:
  version: 2

  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow 
      - test:
          requires:
            - downstream
    