version: 2.1

executors:
  gobuild_and_test:
    docker:
      - image: circleci/golang:1.14
        environment:
          VAULT_ADDR: "http://vault:8200"
          VAULT_TOKEN: root
          VAULT_TEST_APPID: testing
          VAULT_TEST_USERID: asdf
          VAULT_TEST_TOKEN: root
          VAULT_DEV_ALREADY_RUNNING: 1
      - image: quay.io/dollarshaveclub/vault-dev:master
        name: vault
        environment:      
          VAULT_ADDR: "http://0.0.0.0:8200"  
          VAULT_USE_APP_ID: 1
          VAULT_SECRETS_FILE: /go/src/github.com/dollarshaveclub/pvc/testing/vault_secrets.json
          VAULT_APP_ID_FILE: /go/src/github.com/dollarshaveclub/pvc/testing/vault_app_ids.json
          VAULT_POLICIES_FILE: /go/src/github.com/dollarshaveclub/pvc/testing/vault_policies.json
          VAULT_TEST_APPID: testing
          VAULT_TEST_USERID: asdf
          VAULT_TOKEN: root
    working_directory: /go/src/github.com/dollarshaveclub/pvc
jobs:
  flow:
    executor: gobuild_and_test
    steps: 
      - checkout
      - run: go build
      - run: sleep 30
      - run: go test -v -race -cover

workflows:
  version: 2

  btd:
    jobs:
      - flow
