version: 2.1

executors:
  gobuild:
    docker:
      - image: circleci/golang:1.14
        environment:
          VAULT_ADDR: "http://localhost:8200"
          VAULT_TOKEN: root
          VAULT_TEST_APPID: testing
          VAULT_TEST_USERID: asdf
          VAULT_TEST_TOKEN: root
          VAULT_DEV_ALREADY_RUNNING: 1
    working_directory: /go/src/github.com/dollarshaveclub/pvc
    
  test:
    docker:
      - image: circleci/golang:1.14
        environment:
          VAULT_ADDR: "http://localhost:8200"
          VAULT_TOKEN: root
          VAULT_TEST_APPID: testing
          VAULT_TEST_USERID: asdf
          VAULT_TEST_TOKEN: root
          VAULT_DEV_ALREADY_RUNNING: 1
    working_directory: /go/src/github.com/dollarshaveclub/pvc
      - image: quay.io/dollarshaveclub/vault-dev:master
        environment:
          VAULT_USE_APP_ID: 1
          VAULT_SECRETS_FILE: /tmp/opt/secrets.json
jobs:
  flow:
    executor: gobuild
    steps: 
      - checkout
      - run: go build
      - run: mkdir -p /tmp/opt
      - run: docker cp /go/src/github.com/dollarshaveclub/pvc/testing/vault_secrets.json /tmp/opt/secrets.json
      - persist_to_workspace: 
          root: /tmp/opt
          paths:
            - secrets.json
     
  downstream:
    executor: test
    steps: 
      - attach_workspace:
          at: /tmp/opt

      - run: go test -v -race -cover
        
    
    steps:
      - checkout
      - run:
          name: Run Tests
          command: go test -v -race -cover

workflows:
  version: 2

btd:
  jobs:
    - flow:
    - downstream:
        requires:
          - flow 
          