version: 2.1

executors:
  copy_vault_testing_files:
    docker: 
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/dollarshaveclub/pvc

  gobuild_and_test:
    docker:
      - image: circleci/golang:1.14
        environment:
          VAULT_ADDR: "http://localhost:8200"
          VAULT_TOKEN: root
          VAULT_TEST_APPID: testing
          VAULT_TEST_USERID: asdf
          VAULT_TEST_TOKEN: root
          VAULT_DEV_ALREADY_RUNNING: 1
      - image: quay.io/dollarshaveclub/vault-dev:master
        name: vault
        environment:      
          VAULT_ADDR: "http://0.0.0.0:8200"  
          VAULT_USE_APP_ID: 1
          VAULT_SECRETS_FILE: vault_secrets.json
          VAULT_APP_ID_FILE: vault_app_ids.json
          VAULT_POLICIES_FILE: vault_policies.json
          VAULT_TEST_APPID: testing
          VAULT_TEST_USERID: asdf
          VAULT_TOKEN: root
    working_directory: /go/src/github.com/dollarshaveclub/pvc
jobs:
  copy: 
    executor: copy_vault_testing_files
    steps: 
      - checkout
      - run: mkdir -p /tmp/opt
      - run: cp /go/src/github.com/dollarshaveclub/pvc/testing/vault_policies.json /tmp/opt/vault_policies.json
      - run: cp /go/src/github.com/dollarshaveclub/pvc/testing/vault_app_ids.json /tmp/opt/vault_app_ids.json
      - run: cp /go/src/github.com/dollarshaveclub/pvc/testing/vault_secrets.json /tmp/opt/vault_secrets.json
      - persist_to_workspace: 
          root: /tmp/opt
          paths:
            - vault_secrets.json
            - vault_app_ids.json
            - vault_policies.json
    
  test:
    executor: gobuild_and_test
    steps: 
      - attach_workspace:
          at: .
      - checkout
      - run: sleep 30
      - run: go test -v -race -cover

workflows:
  version: 2

  btd:
    jobs:
      - copy
      - test:
          requires:
            - copy
